name: napari25
channels:
  - conda-forge
  - bioconda

dependencies:
  - python==3.10
  - jupyterlab
  - watermark
  - napari==0.5.6
  - pyqt==5.15.9
  - numpy<2.0
  - napari-segment-blobs-and-things-with-membranes==0.3.11
  - napari-skimage-regionprops==0.10.1
  - napari-accelerated-pixel-and-object-classification==0.14.1
  - seaborn==0.13.2
  - omero-py==5.16.1
  - ezomero==3.1.1
  - pip
  - pip:
    - napari-omero==0.5.1
    - napari-clusters-plotter==0.9.0
